//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApi.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uplate
    {
        public long Id { get; set; }
        public string DuznikNalogodavac { get; set; }
        public string SvrhaPlacanja { get; set; }
        public string PoverilacPrimalac { get; set; }
        public string MestoDatumPrijema { get; set; }
        public string SifraPlacanja { get; set; }
        public int Cena { get; set; }
        public string RacunDuznikaNalogodavca { get; set; }
        public string Model { get; set; }
        public string PozivNaBrojZaduzenja { get; set; }
        public string RecunPoveriocaPrimaoca { get; set; }
        public string Model2 { get; set; }
        public string RacunNaBrojOdobrenje { get; set; }
        public string DatumValute { get; set; }
        public bool Hitno { get; set; }
        public System.DateTime DatumUplate { get; set; }
        public bool IzvrsenaUplata { get; set; }
    }
}
